apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-ash
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-ash
    spec:
      containers:
      - name: nginx-ash
        image: nginx:1.14.2
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx-ash
  labels: 
    app: nginx-ash
spec:
  type: LoadBalancer
  ports:
    - port: 8765
      targetPort: 9376
  selector:
    app: nginx-ash        